# Site settings
title: Tech Stew
email: xaypeala # formspree.io id 
url: https://techstew.no
description: "Tech Stew is a norwegian tech company focused on building useful and fun apps"
keywords: "apps, tech, consultant, hoopteller"
skills: "Modern Web & App Development - React & React Native"
meta_author: Seppola Sindre

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4AB3E4 #80B3FF
  primary-rgb: "74,179,228" #"128,179,255"
  secondary: 7886A3 #FD6E8A
  secondary-dark: 2F6094 #A2122F

# Footer settings
footer:
  copyright: Tech Stew AS
  location: Location
  social: Around the Web
  credits: Credits

# Social networks (alt: facebook, stack-overflow, bitbucket, google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sseppola
  - title: github
    url: http://github.com/tech-stew

# Postal address (add as many lines as necessary)
address:
  - line: Tech Stew AS
  - line: c/o Zpecter Økonomi
  - line: Fjordveien 3
  - line: 1363 Høvik, Norway

# Credits content
credits: 'Site built using the "Freelancer" theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
